### ISSUE TITLE
UCG_COM_MSG_SEND_CD_DATA_SEQUENCE Bug

### ISSUE THREAD

**Issue by GoogleCodeExporter** [olikraus/ucglib#24]
```
Setting of the A0/RS/CD line depends on the configuration, but is fixed in the 
the .cpp file
--> fixe code for message UCG_COM_MSG_SEND_CD_DATA_SEQUENCE

```

Original issue reported on code.google.com by `olikr...@gmail.com` on 2 May 2014 at 11:31

**Comment by olikraus** [comment]
This is not a bug: UCG_CFG_CD and UCG_COM_MSG_SEND_CD_DATA_SEQUENCE are independent. UCG_COM_MSG_SEND_CD_DATA_SEQUENCE is and can be hardware dependent. Anything else will be too complicated.
