### ISSUE TITLE
Support power down for all display types

### ISSUE THREAD

**Issue by GoogleCodeExporter** [olikraus/ucglib#27]
```

all ucg_dev_ic... should  support power down.

```

Original issue reported on code.google.com by `olikr...@gmail.com` on 8 Jun 2014 at 12:41

**Comment by olikraus** [comment]
ok, this needs to be checked

**Comment by olikraus** [comment]
ucg_dev_ic_st7735.c  --> implemented & tested
ucg_dev_ic_ssd1351.c --> implemented
ucg_dev_ic_pcf8833.c
ucg_dev_ic_ld50t6160.c
ucg_dev_ic_ili9341.c --> implemented & tested
ucg_dev_ic_ili9325.c

**Comment by olikraus** [comment]
done
