### ISSUE TITLE
make bdf2ucg avialable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [olikraus/ucglib#31]
```

- windows exe
- help page
```

Original issue reported on code.google.com by `olikr...@gmail.com` on 19 Aug 2014 at 5:10

**Comment by olikraus** [comment]
Now available at

https://drive.google.com/folderview?id=0B5b6Dv0wCeCRfi1xM0l5eDdzSnhiSHY3X3JXZi0wOHZFNzRYOTZEZ0M5ZWp1Z3BTYzhkU2M&usp=sharing
