### ISSUE TITLE
new names for fonts

### ISSUE THREAD

**Issue by RogerSchaefer** [olikraus/ucglib#59]
I was unhappy to find the fonts in the new version of ucglib have been renamed.  The new fonts have suffixes like _hf  _hb  _hr  _tf  _tr   and for number only fonts _hn  _tn   These are only a few; there are others.  

I have a dozen & a half sketches using ucglib each with perhaps a half dozen different fonts.  This will cause me a LOT of work to find the proper suffix for a font name and edit it.

Is there any shortcut?

Roger

**Comment by olikraus** [comment]
I am sorry for the problems. Yet, my hope was to make the font naming more consistent.
