### ISSUE TITLE
Draw glyphs or images without a font

### ISSUE THREAD

**Issue by hspeedy** [olikraus/ucglib#66]
Is it possible to draw images without creating a font?
I tried to create a font using Fony and your bdf converter.
This didn't work for me because something is missing.
The created file was always the same. Is there something
I need to know? I'm sure this would be a good way but
there should be more information in your wiki about doing
this.

Greetings Heiko

**Comment by hspeedy** [comment]
Okay, now it works. Seems as I have to start at 0x20 with this font. My last tries where from 0x00 to 0x0B.

**Comment by TCB13** [comment]
@hspeedy can you share how you created the font and load it?

**Comment by hspeedy** [comment]
i have used a tool to create fonts by import or drawing the characters with pixels. i don't remember the name. seemed to be an old win32 tool. at the end there have been different export option like ttf or a code fornat consisting of a large byte array to use in code.

**Comment by TCB13** [comment]
@hspeedy thank you for taking the time to answer me. If you've ever come across the tool's name let me know :)

Meanwhile I'll be using the Adafruit GFX that for all its defects makes it way easier to print glyphs / convert fonts etc.
