### ISSUE TITLE
cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'volatile uint8_t* 

### ISSUE THREAD

**Issue by nabulsi** [olikraus/ucglib#79]
Hi,

I have an ILI9341 display. I am using the latest Arduino (1.8.5) and latest Ucglib (1.4.0). I have tried on 2 different machines, MAC & Windows, but still getting the same error:
`/Users/xxxx/Documents/Arduino/libraries/Ucglib/src/Ucglib_orig.cpp: In function 'void ucg_com_arduino_init_8bit(ucg_t*)':
/Users/xxxxx/Documents/Arduino/libraries/Ucglib/src/Ucglib_orig.cpp:786:20: error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in assignment
   u8g_data_port[0] =  portOutputRegister(digitalPinToPort(ucg->pin_list[UCG_PIN_D0]));`

there are in total 9 errors like this (i.e. from u8g_data_port[0] to [8]). In addition, in both machines I see the library under "Incompatible" when going to "File --> Examples".

This is my constructor:
`Ucglib_ILI9341_18x240x320_SWSPI ucg(/*sclk=*/ 18, /*data=*/ 23, /*cd=*/ 13 , /*cs=*/ 5, /*reset=*/ 19);`
My code is the HelloWorld from the Ucglib

Thanks

**Comment by nabulsi** [comment]
Anyone is able to shed some light here please?

Thanks

**Comment by olikraus** [comment]
which board? 
I think it will be fixed for 1.5.x

**Comment by nabulsi** [comment]
2 boards:
   ESP32-DevKitC & SparkFun ESP32

**Comment by olikraus** [comment]
Yes, this is fixed. I had the same issue with the ESP32 boards.
